---
- hosts: all
  gather_facts: False
  serial: 1
  name: Execute a script.
  remote_user: rchivate
  #become: True
  vars_files:
    - pas.yml
  tasks:
     
     - name: Disable selected services of host
       #raw: curl -u rchivate:{{ ssh_pass }} -d "cmd_typ=28&cmd_mod=2&host={{ item }}&btnSubmit=Commit" "http://{{ inventory_hostname }}/nagios3/cgi-bin/cmd.cgi"
       raw: curl -u rchivate:{{ ssh_pass }} -d "cmd_typ=23&cmd_mod=2&host={{ item }}&service=check_raid&btnSubmit=Commit" "http://{{ inventory_hostname }}/nagios3/cgi-bin/cmd.cgi"
       with_items: [god-save00-vnx-pr,god-save01-vnx-pr]     
     
     #- name: Enable host notif
       #raw: curl -u rchivate:{{ ssh_pass }} -d "cmd_typ=24&cmd_mod=2&host={{ item }}&btnSubmit=Commit" "http://{{ inventory_hostname }}/nagios3/cgi-bin/cmd.cgi"
       #raw: curl -u rchivate:{{ ssh_pass }} -d "cmd_typ=24&cmd_mod=2&host={{ item }}&service=CPU&btnSubmit=Commit" "http://{{ inventory_hostname }}/nagios3/cgi-bin/cmd.cgi"
       #with_items: [god-proxy02-vnx-pr]
