---
- hosts: all
  gather_facts: False
  serial: 1
  name: Execute a script.
  remote_user: rchivate
  #become: True
  vars_files:
    - pas.yml
  tasks:
     
     - name: Enable all services of host
       #raw: curl -u rchivate:{{ ssh_pass }} -d "cmd_typ=28&cmd_mod=2&host={{ item }}&btnSubmit=Commit" "http://{{ inventory_hostname }}/nagios3/cgi-bin/cmd.cgi"
       raw: curl -u rchivate:{{ ssh_pass }} -d "cmd_typ=22&cmd_mod=2&host={{ item.machine }}&service={{ item.services }}&btnSubmit=Commit" "http://{{ inventory_hostname }}/nagios3/cgi-bin/cmd.cgi"
       with_items:
         - { machine: adm-cacti00-lyo2-pr, services: "space_disk", "url_cacti" }
         - { machine: adm-cacti01-lyo2-pr, services: ["space_disk, url_cacti"] }
    
