---
- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
   - name: Delete defination of un-wanted machines
     raw: sed -i ':a;N;s/\n/&/4;Ta;/{{ item }}/!{P;D};:b;N;s/\n/&/6;Tb;d' sup_extra_god_cbv4.tpl
     with_items: [10.111.205.144,10.111.205.146,10.111.205.150,10.111.205.161]
 
 
 
- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Delete string
    replace:
     path: sup_extra_god_cbv4.tpl
     regexp: "{{ item }}"
     replace: ''
    with_items: ['god-game05-cbv4-pr,','god-game07-cbv4-pr,','god-game11-cbv4-pr,']

