---
- name: gather fact
  hosts: 127.0.0.1
  tasks:
  - name: Get VM facts
    vmware_guest_facts:
       hostname: "{{ hostname }}"
       username: "{{ username }}"
       password: "{{ password }}"
       validate_certs: no
       name: "{{ vm_name}} "
    register: my_vm
