---
- hosts: all
  gather_facts: False
  serial: 1
  name: Execute a script.
  remote_user: rchivate
  #become: True
  vars_files:
    - pas.yml
  tasks:
     
     - name: Enable all services of host
       raw: curl -u rchivate:{{ ssh_pass }} -d "cmd_typ=28&cmd_mod=2&host={{ item }}&btnSubmit=Commit" "http://{{ inventory_hostname }}/nagios3/cgi-bin/cmd.cgi"
      # with_items: [adm-cacti01-bdx1-pr,adm-cacti00-bdx1-pr]     
     
     - name: Enable host notif
       raw: curl -u rchivate:{{ ssh_pass }} -d "cmd_typ=24&cmd_mod=2&host={{ item }}&btnSubmit=Commit" "http://{{ inventory_hostname }}/nagios3/cgi-bin/cmd.cgi"
      # with_items: [adm-cacti01-bdx1-pr,adm-cacti00-bdx1-pr]
