- name: gather fact
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name : "creation de VM via script"
    vsphere_guest:
        vcenter_hostname: 10.69.115.27
        username: u157740
        password: Zaqwpmnb99
        guest: "{{vmname}}"
        state: powered_off
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: demande d'Emile
          folder: NADC
        vm_disk:
          disk1:
            size_gb: "{{tailledisque}}"
            type: thin
            datastore: SAN-NMS05CH_LINUX
            # VMs can be put into folders. The value given here is either the full path
            # to the folder (e.g. production/customerA/lamp) or just the last component
            # of the path (e.g. lamp):
            # folder: production/customerA/lamp
        vm_nic:

          nic1:
            type: vmxnet3
            network: dvPG-CHP-M2M-744-NATBv
            network_type: standard
          nic2:
            type: vmxnet3
            network: dvPG-CHP-PO-135-NATBv
            network_type: standard
          nic3:
            type: vmxnet3
            network: dvPG-CHP-NE-104-NATBv
            network_type: standard
        vm_hardware:
          memory_mb: "{{memoire}}"
          num_cpus: "{{nombrecpu}}"
          osid: rhel6_64Guest
          scsi: paravirtual
        cluster: sfrchp-3 (UCS)
        esxi:
          datacenter: neufnms
          hostname: blesx512ch.nms.ld
        validate_certs: no
    register: var
  - debug: msg="{{var.ansible_facts}}"
    when: var.ansible_facts is defined

