---
- hosts: all
  remote_user: extprodpfs
  become: yes
  tasks:
    - name: Install Packages 
      yum:
        name:
          - nrpe 
          - nagios-plugins-users 
          - nagios-plugins-load 
          - nagios-plugins-swap 
          - nagios-plugins-disk 
          - nagios-plugins-procs

        #disablerepo: "env-ext-java1.8-sun-yss,env-ext-mongodb3.2-yss,env-ext-postgresql9.6-yss,env-ext-tomcat7.0-yss,ext-jbossas10-yss,ext-yss,extras,prod-yss,ptin-yss,sol-misc-yss,updates"
        enablerepo: epel
        state: present
